# <span style="color:darkblue"> Lecture 3: Mathematical Operations and Random Numbers </span>

<font size="5"> 

In the previous class we:
- Introduced lists and variable types
- Talked about how to extract elements from a list

<font size="5"> 

In this class we will:

- Introduce a library for general mathematical operations
- Generate random numbers
- (Optional) Matrix operations

## <span style="color:darkblue"> I. Import Libraries </span>

In [1]:
# the "numPy" library is used for mathematical operations
# the "matplotlib" library is for generating graphs

import numpy as np
import matplotlib.pyplot as plt


##  <span style="color:darkblue"> II. Numbers and Functions </span>

<font size = "5" >
Examples of numPy numbers

In [2]:
# Computes "pi" (3.14...)

np.pi

3.141592653589793

<font size = "5" >

Examples of numPy functions

$ ln(x), e^x, sin(x), cos(x), \sqrt{x}$

In [6]:
# log(x) computes the logarithm with base "e" (Euler constant)
# exp(x) compute the Euler constant raised to the power of "x"
# sing(x) computes the sine of x
# cos(x) computes the cosine of x
# In this example, we're substituting x = 1

print(np.log(1))
print(np.exp(1))
print(np.sin(1))
print(np.cos(1))
print(np.sqrt(1))

0.0
2.718281828459045
0.8414709848078965
0.5403023058681398
1.0


<font size = "5">

Try it yourself!

- Create a new variable, $x = 5$
- Compute $\pi x^2$
- Compute $ \frac{1}{\sqrt{2\pi}}e^{-x^2} $

In [15]:
# Include your answer here:

x = 5
print(np.pi*(x^2))
print((1/np.sqrt(2*np.pi))*np.exp(-x^2))

21.991148575128552
0.0003637882707952594


##  <span style="color:darkblue"> III. Vector Arrays </span>

<font size = "5">
Create an array from a list

$ \text{ }$
$ a = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}
\qquad b = \begin{pmatrix} 0 \\ 1 \\ 0\end{pmatrix}
\qquad c = \begin{pmatrix} 10 \\ 100 \\ 1000 \\ 2000 \\ 5000 \end{pmatrix} 
\qquad d = \begin{pmatrix} 4 \\ 2 \end{pmatrix} $

In [23]:
# You create an array by converting a list [1,2,3] to a numeric object
# "array" is a subfunction of the library numPy.

vec_a  = np.array([1,2,3])
vec_b  = np.array([0,1,0])
vec_c  = np.array([10,100,1000,2000,5000])


<font size = "5">

Accessing an element of an array

In [8]:
# Arrays, like lists, start their numbering at zero.
# You also access them with square brackets

print(vec_a[0])
print(vec_a[2])


1
3


<font size = "5">
Operations with a single array and a scalar

<font size = "5">

$ a + 2 = \begin{pmatrix} a_1 + 2 \\ a_2 + 2 \\ a_3 + 2 \end{pmatrix}$

In [9]:
# A scalar refers to either an int or float
# We can do many common operations with 

print(vec_a * 2)
print(vec_a / 2)
print(vec_a + 2)
print(vec_a ** 2)

[2 4 6]
[0.5 1.  1.5]
[3 4 5]
[1 4 9]


<font size = "5">
Element-by-element addition between two arrays of the same size

$\text{ }$

$ a + b = \begin{pmatrix} a_1 \\ a_2 \\ a_3 \end{pmatrix} +
          \begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix} =
          \begin{pmatrix} a_1 + b_1 \\ a_2 + b_2 \\ a_3 + b_3 \end{pmatrix}$

In [10]:
# When you add two arrays of the same size,
# Python adds the individual elements in each position

print(vec_a + vec_b)


[1 3 3]


<font size ="5">

The default multiplication option is element-by element:

$ a * b = \begin{pmatrix} a_1 * b_1 \\ a_2 * b_2 \\ a_3 * b_3 \end{pmatrix}$

In [11]:
# We can do other similar element-by-element operations
# such as multiplication, subtraction, and division.

print(vec_a * vec_b)
print(vec_a - vec_b)
print(vec_a / vec_b)


[0 2 0]
[1 1 3]
[inf  2. inf]


/var/folders/1b/jzb9ndz97b5260fzr9d8kzyh5f7xd6/T/ipykernel_59016/3839639845.py:6: RuntimeWarning: divide by zero encountered in true_divide
  print(vec_a / vec_b)


<font size = "5">
Summary statistics of an array

In [12]:
# The function np.mean() computes the mean of an array
# We can do similar operations for the standard deviation (std),
# the minimum (min), the median (median), and the maximum (max).

print(np.mean(vec_a))
print(np.std(vec_a))
print(np.min(vec_a))
print(np.median(vec_a))
print(np.max(vec_a))

2.0
0.816496580927726
1
2.0
3


<font size = "5">

Try it yourself! Compute the mean of


$ e = \begin{pmatrix} 10 \\ 8 \\ 15 \\ 0 \\ 24 \end{pmatrix} $

In [31]:
# Create your own array and compute any of the above summary statistics

vec_e = np.array([10, 8, 15, 0, 24])
print(vec_e[0])
print(type(vec_e))
vec_k = np.array([vec_e + 2])
print(vec_e + vec_k)
print(type(vec_k))
print(np.mean(vec_e))





10
<class 'numpy.ndarray'>
[[22 18 32  2 50]]
<class 'numpy.ndarray'>
11.4


<font size = "5">
<span style="color:red"> Common Pitfall </span>: Make sure that the arrays have the same size

In [34]:
# Here I try to combine two arrays of different size.

vec_a + vec_c

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

##  <span style="color:darkblue"> IV. Random Numbers </span>

<font size = "5">

Why randomness?

- Simulate different scenarios: high risk or low risk
- Study properties of a complex system and/or estimator
- In medicine, randomly assign subjects to treatment or control

<font size = "5">

Create a vector of random variables

In [48]:
# This code creates a vector of random variables 
# generated from a normal distribution with
# mean "loc" (location) and standard deviation "scale"
# the number of distinct variabels is "size"

randomvar_a = np.random.normal(loc=0, scale=1, size=10)
print(randomvar_a)

[ 0.44222864  0.63894043 -1.37446701 -0.62347418 -0.93995172  0.95701507
  0.09401858 -1.17927242 -1.32434818 -1.65615069]


<font size = "5">

Random numbers differ every time!

- Avoid this problem by drawing from a "pregenerated" set.
- This is called a seed

In [50]:
# Your computer will typically generate different numbers every time you run a command
# However, sometimes you want to be able to replicate the results
# You can choose any other number instead of "12345". This will produce another set
# of random numbers, but they will give the same answers

np.random.seed(12345)

random_var_b = np.random.normal(loc=0, scale=1, size=10)
print(random_var_b)

[-0.20470766  0.47894334 -0.51943872 -0.5557303   1.96578057  1.39340583
  0.09290788  0.28174615  0.76902257  1.24643474]


<font size = "5">

Compute a histogram with the results

In [57]:
# Compute a histogram
# You can edit the number of bins with plt.hist(x = randomvar_a)

randomvar_x = np.random.normal(loc=0, scale=1, size=10)

plt.hist(x = randomvar_x)
plt.xlabel("Variable a")
plt.ylabel("Frequency")

Text(0, 0.5, 'Frequency')

<font size = "5">

Try this again with $size = 100, 1000, 10000$

In [60]:
# Write the code for your histogram

np.random.seed(1000)
randomvar_x = np.random.normal(loc=(0), scale=(1), size=100)
plt.(randomvar_x)



[-0.8044583   0.32093155 -0.02548288  0.64432383 -0.30079667  0.38947455
 -0.1074373  -0.47998308  0.5950355  -0.46466753  0.66728131 -0.80611561
 -1.19606983 -0.40596016 -0.18237734  0.10319289 -0.13842199  0.70569237
  1.27179528 -0.98674733 -0.33483545 -0.0994817   0.4071921   0.91938754
  0.31211801  1.53316107 -0.55017387 -0.38314741 -0.82294096  1.60008337
 -0.0692813   0.08320949 -0.32692468 -0.04579719 -0.30446006  1.92301013
 -0.078659   -0.58206572 -1.61798224  0.86726082 -1.04043709  0.65042142
  2.69964586  0.80202451 -1.09692126 -0.17805445 -0.42287048 -0.33040055
 -1.11116278 -0.74200575  2.57475919  1.07321332 -1.86613451 -0.64717693
  1.08224081  0.17667032 -0.83532823 -1.69499832  1.13341723  1.04853072
 -2.12832537 -1.43713939  0.17793711  1.39442275  0.29132019 -0.08200619
  0.64424261  0.32807995  0.85743275 -0.93696928  0.18007496 -1.42337059
 -0.36775578 -1.52328799 -0.6347717   0.98740384 -1.01601962  2.04572375
  0.24999852  0.65116253 -1.26602354  1.3741556  -0

# <span style="color:darkblue"> Additional Resources </span>

<font size="5"> 

Check out additional examples at:

- https://allendowney.github.io/ElementsOfDataScience/03_arrays.html




# <span style="color:darkblue"> (Optional) Matrix Operations </span>

<font size="5"> 


<font size = "5">
Creating a matrix by stacking different rows

$ \text{ }$

$ X = \begin{pmatrix} 1 & 2 & 3 \\ 
                       0 & 4 & 5 \\
                       0 & 0 & 6
                       \end{pmatrix} $

In [13]:
# Matrices are usually denoted by capital letters
# The object [[1,2,3],[4,5,6],[7,8,9]] is a list of lists
# It's useful to maintain this notation in the code as well

X = np.array([[1,2,3],[0,4,5],[0,0,6]])
print(X)

[[1 2 3]
 [0 4 5]
 [0 0 6]]


<font size = "5">
Creating a matrix by stacking different columns

$ \text{ } $

$ Y = \begin{pmatrix} 1 & 2 \\ 0 & 1 \\ 1 & 0 \end{pmatrix}$

In [14]:
# You can also stack columns
Y =  np.column_stack([[1,0,1],[2,1,0]])
print(Y)

[[1 2]
 [0 1]
 [1 0]]


<font size = "5">
Transpose

$ \text{ }$

$ Y' = \begin{pmatrix}  1 & 0 & 1 \\ 2 & 1 & 0  \end{pmatrix} $

In [15]:
# Matrix Transpose
np.matrix.transpose(Y)

array([[1, 0, 1],
       [2, 1, 0]])

<font size = "5">

Matrix multiplication

$ XY = \begin{pmatrix} 1 & 2 & 3 \\ 
                       0 & 4 & 5 \\
                       0 & 0 & 6
                       \end{pmatrix}
                       \begin{pmatrix} 1 & 2 \\ 0 & 1 \\ 1 & 0 \end{pmatrix} = 
        \begin{pmatrix} 4 & 4 \\ 5 & 4 \\ 6 & 0 \end{pmatrix} $

In [34]:
# Matrix Multiplication

np.dot(X,Y)

np.matmul(X,Y)

array([[4, 4],
       [5, 4],
       [6, 0]])

<font size = "5">

Matrix inverse

$ X^{-1} = \begin{pmatrix} 1 & 2 & 3 \\ 
                       0 & 4 & 5 \\
                       0 & 0 & 6
                       \end{pmatrix}^{-1} $

In [31]:
# Check the determinant of a matrix (a matrix is invertible if the determinant is not zero)
print(np.linalg.det(X))

# Matrix inverse
# The following command stands for linear algebrar inverse.
X_inv = np.linalg.inv(X)

# Output the result
print(X_inv)


23.999999999999993
[[ 1.         -0.5        -0.08333333]
 [ 0.          0.25       -0.20833333]
 [ 0.          0.          0.16666667]]
[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


<font size = "5">

Try it yourself! Check that this is indeed an inverse:

$X X_{inv} = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$

In [32]:
# Multiply "X" times "X_inv" using the command shown above
# Note: Sometimes the result is shown in scientific notation.





[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
